{
 "title": "risingwave_dashboard",
 "description": "RisingWave Dashboard",
 "tags": [ "risingwave" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(node_num) by (node_type)", "legendFormat": "{{node_type}}" }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes) by (job,instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) by (job,instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Barrier Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "all_barrier_nums", "legendFormat": "all_barrier" },
    { "expr": "in_flight_barrier_nums", "legendFormat": "in_flight_barrier" }
   ]
  },
  {
   "title": "Barrier Send Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_send_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_send_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_send_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_send_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_send_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_send_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_send_duration_seconds_sum[$__rate_interval]) / rate(meta_barrier_send_duration_seconds_count[$__rate_interval])",
     "legendFormat": "barrier_send_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_duration_seconds_sum[$__rate_interval]) / rate(meta_barrier_duration_seconds_count[$__rate_interval])",
     "legendFormat": "barrier_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier In-Flight Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(stream_barrier_inflight_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(stream_barrier_inflight_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(stream_barrier_inflight_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(stream_barrier_inflight_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(stream_barrier_inflight_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_inflight_latency_pmax"
    },
    {
     "expr": "max(sum by(le, instance)(rate(stream_barrier_inflight_duration_seconds_sum[$__rate_interval]))  / sum by(le, instance)(rate(stream_barrier_inflight_duration_seconds_count[$__rate_interval])))",
     "legendFormat": "barrier_inflight_latency_avg"
    }
   ]
  },
  {
   "title": "Barrier Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket[$__rate_interval])) by (le,instance))",
     "legendFormat": "barrier_sync_latency_p50 - computer @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket[$__rate_interval])) by (le,instance))",
     "legendFormat": "barrier_sync_latency_p90 - computer @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket[$__rate_interval])) by (le,instance))",
     "legendFormat": "barrier_sync_latency_p99 - computer @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket[$__rate_interval])) by (le,instance))",
     "legendFormat": "barrier_sync_latency_p999 - computer @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(stream_barrier_sync_storage_duration_seconds_bucket[$__rate_interval])) by (le,instance))",
     "legendFormat": "barrier_sync_latency_pmax - computer @ {{instance}}"
    },
    {
     "expr": "sum by(le, instance)(rate(stream_barrier_sync_storage_duration_seconds_sum[$__rate_interval]))  / sum by(le, instance)(rate(stream_barrier_sync_storage_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "barrier_sync_latency_avg - computer @ {{instance}}"
    }
   ]
  },
  {
   "title": "Barrier Wait Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_p999"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(meta_barrier_wait_commit_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "barrier_wait_commit_latency_pmax"
    },
    {
     "expr": "rate(meta_barrier_wait_commit_duration_seconds_sum[$__rate_interval]) / rate(meta_barrier_wait_commit_duration_seconds_count[$__rate_interval])",
     "legendFormat": "barrier_wait_commit_avg"
    }
   ]
  },
  {
   "title": "Source Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "rate(stream_source_output_rows_counts[$__rate_interval])",
     "legendFormat": "source={{source_id}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Source Throughput Per Partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "rows/s" } },
   "targets": [
    {
     "expr": "rate(partition_input_count[$__rate_interval])",
     "legendFormat": "actor={{actor_id}} source={{source_id}} partition={{partition}}"
    }
   ]
  },
  {
   "title": "Streaming Actors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "rows/s" } },
     "targets": [
      {
       "expr": "rate(stream_executor_row_count[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}->{{executor_id}}"
      }
     ]
    },
    {
     "title": "Actor Sampled Deserialization Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "actor_sampled_deserialize_duration_ns",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Sampled Serialization Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "actor_sampled_serialize_duration_ns",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Backpressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_actor_output_buffer_blocking_duration_ns[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Input Blocking Time Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_actor_input_buffer_blocking_duration_ns[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}->{{upstream_fragment_id}}"
      }
     ]
    },
    {
     "title": "Actor Barrier Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_barrier_time[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Processing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_processing_time[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Execution Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_actor_execution_time[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Input Row",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "rate(stream_actor_in_record_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Actor Output Row",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "rate(stream_actor_out_record_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_duration[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Fast Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_fast_poll_duration[$__rate_interval]) / rate(stream_actor_fast_poll_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_duration[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Slow Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_slow_poll_duration[$__rate_interval]) / rate(stream_actor_slow_poll_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_duration[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Poll Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_poll_duration[$__rate_interval]) / rate(stream_actor_poll_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_duration[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Idle Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_idle_duration[$__rate_interval]) / rate(stream_actor_idle_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Total Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_duration[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Tokio: Actor Scheduled Avg Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(stream_actor_scheduled_duration[$__rate_interval]) / rate(stream_actor_scheduled_cnt[$__rate_interval]) > 0",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Join Executor Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(stream_join_lookup_miss_count[$__rate_interval])",
       "legendFormat": "cache miss {{actor_id}} {{side}}"
      },
      {
       "expr": "rate(stream_join_lookup_total_count[$__rate_interval])",
       "legendFormat": "total lookups {{actor_id}} {{side}}"
      }
     ]
    },
    {
     "title": "Join Executor Barrier Align",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(stream_join_barrier_align_duration_bucket[$__rate_interval])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "p90 {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(stream_join_barrier_align_duration_bucket[$__rate_interval])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "p99 {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(stream_join_barrier_align_duration_bucket[$__rate_interval])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "p999 {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(1.0, sum(rate(stream_join_barrier_align_duration_bucket[$__rate_interval])) by (le, actor_id, wait_side, job, instance))",
       "legendFormat": "pmax {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum by(le, actor_id, wait_side, job, instance)(rate(stream_join_barrier_align_duration_sum[$__rate_interval])) / sum by(le,actor_id,wait_side,job,instance) (rate(stream_join_barrier_align_duration_count[$__rate_interval]))",
       "legendFormat": "avg {{actor_id}}.{{wait_side}} - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Join Actor Input Blocking Time Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(stream_join_actor_input_waiting_duration_ns[$__rate_interval]) / 1000000000",
       "legendFormat": "{{actor_id}}"
      }
     ]
    },
    {
     "title": "Join Cached Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "targets": [
      { "expr": "stream_join_cached_entries", "legendFormat": "{{actor_id}} {{side}}" }
     ]
    },
    {
     "title": "Join Cached Rows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "targets": [
      { "expr": "stream_join_cached_rows", "legendFormat": "{{actor_id}} {{side}}" }
     ]
    },
    {
     "title": "Join Cached Estimated Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "stream_join_cached_estimated_size",
       "legendFormat": "{{actor_id}} {{side}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Streaming Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchange Send Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_send_size[$__rate_interval])",
       "legendFormat": "{{up_actor_id}}->{{down_actor_id}}"
      }
     ]
    },
    {
     "title": "Exchange Recv Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_recv_size[$__rate_interval])",
       "legendFormat": "{{up_actor_id}}->{{down_actor_id}}"
      }
     ]
    },
    {
     "title": "Fragment Exchange Send Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_frag_send_size[$__rate_interval])",
       "legendFormat": "{{up_fragment_id}}->{{down_fragment_id}}"
      }
     ]
    },
    {
     "title": "Fragment Exchange Recv Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(stream_exchange_frag_recv_size[$__rate_interval])",
       "legendFormat": "{{up_fragment_id}}->{{down_fragment_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Batch Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchange Recv Row Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "row" } },
     "targets": [
      {
       "expr": "batch_exchange_recv_row_number",
       "legendFormat": "{{query_id}} : {{source_stage_id}}.{{source_task_id}} -> {{target_stage_id}}.{{target_task_id}}"
      }
     ]
    }
   ]
  },
  { "title": "Hummock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Build and Sync Sstable Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(state_store_shared_buffer_to_l0_duration_sum[$__rate_interval])) / sum by(le, job, instance) (rate(state_store_shared_buffer_to_l0_duration_count[$__rate_interval]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_sst_store_block_request_counts[$__rate_interval])) by (job, instance, type)",
     "legendFormat": "{{type}} - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(file_cache_get_latency_count[$__rate_interval])) by (instance)",
     "legendFormat": "file cache get @ {{instance}}"
    },
    {
     "expr": "sum(rate(file_cache_miss[$__rate_interval])) by (instance)",
     "legendFormat": "file cache miss @ {{instance}}"
    },
    {
     "expr": "sum(rate(file_cache_insert_latency_count[$__rate_interval])) by (instance)",
     "legendFormat": "file cache insert @ {{instance}}"
    },
    {
     "expr": "sum(rate(file_cache_erase_latency_count[$__rate_interval])) by (instance)",
     "legendFormat": "file cache erase @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_get_duration_count[$__rate_interval])) by (job,instance)",
     "legendFormat": "get - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_scan_duration_count[$__rate_interval])) by (job,instance)",
     "legendFormat": "forward scan - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_reverse_scan_duration_count[$__rate_interval])) by (job,instance)",
     "legendFormat": "backward scan - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_get_shared_buffer_hit_counts[$__rate_interval])) by (job,instance)",
     "legendFormat": "shared_buffer hit - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_iter_in_process_counts[$__rate_interval])) by(job,instance)",
     "legendFormat": "iter - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(state_store_get_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(state_store_get_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_get_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_get_duration_sum[$__rate_interval])) / sum by(le, job, instance) (rate(state_store_get_duration_count[$__rate_interval]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(state_store_range_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "Forward p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(state_store_range_scan_duration_bucket[$__rate_interval])) by (le,job, instance))",
     "legendFormat": "Forward p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "Forward p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_range_scan_duration_sum[$__rate_interval])) / sum by(le, job,instance) (rate(state_store_range_scan_duration_count[$__rate_interval]))",
     "legendFormat": "Forward avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(state_store_range_reverse_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "Backward p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(state_store_range_reverse_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "Backward p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_reverse_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "Backward p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_range_reverse_scan_duration_sum[$__rate_interval])) / sum by(le, job, instance) (rate(state_store_range_reverse_scan_duration_count[$__rate_interval]))",
     "legendFormat": "Backward avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_iter_duration_sum[$__rate_interval])) / sum by(le, job,instance) (rate(state_store_iter_duration_count[$__rate_interval]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Duration - Iter Pure Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_scan_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_scan_iter_duration_sum[$__rate_interval])) / sum by(le, job,instance) (rate(state_store_iter_scan_duration_count[$__rate_interval]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_get_key_size_bucket[$__rate_interval])) by (le, job, instance)) + histogram_quantile(0.9, sum(rate(state_store_get_value_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_get_key_size_bucket[$__rate_interval])) by (le, job, instance)) + histogram_quantile(0.99, sum(rate(state_store_get_value_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_get_key_size_bucket[$__rate_interval])) by (le, job, instance)) + histogram_quantile(0.999, sum(rate(state_store_get_value_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_range_scan_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "forward scan p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_scan_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "forward scan p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_range_scan_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "forward scan p999 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_range_reverse_scan_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "backward scan p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_range_reverse_scan_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "backward scan p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_range_reverse_scan_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "backward scan p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Size - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_size_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Item Count - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_iter_item_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_iter_item_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(state_store_iter_item_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "p999 - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Throughput - Get",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(rate(state_store_get_key_size_sum[$__rate_interval])) by(job, instance) + sum(rate(state_store_get_value_size_sum[$__rate_interval])) by(job, instance)) / (sum(rate(state_store_get_key_size_count[$__rate_interval])) by (job, instance) + sum(rate(state_store_get_value_size_count[$__rate_interval])) by (job, instance))",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Throughput - Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_range_scan_size_sum[$__rate_interval])) by(job, instance) / sum(rate(state_store_range_scan_size_count[$__rate_interval])) by (job, instance)",
     "legendFormat": "forward - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_range_reverse_scan_size_sum[$__rate_interval])) by(job, instance) / sum(rate(state_store_range_reverse_scan_size_count[$__rate_interval])) by (job, instance)",
     "legendFormat": "backward - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Throughput - Iter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_size_sum[$__rate_interval])) by(job, instance) / sum(rate(state_store_iter_size_count[$__rate_interval])) by (job, instance)",
     "legendFormat": "{{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Bloom Filter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_bloom_filter_true_negative_counts[$__rate_interval])) by (job,instance)",
     "legendFormat": "bloom filter true negative  - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_bloom_filter_check_counts[$__rate_interval])) by (job,instance)",
     "legendFormat": "bloom filter check count  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Iter keys flow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_iter_scan_key_counts[$__rate_interval])) by (instance, type)",
     "legendFormat": "iter keys flow - {{type}} @ {{instance}} "
    }
   ]
  },
  {
   "title": " Filter-Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(state_store_bloom_filter_true_negative_counts[$__rate_interval])) by (job,instance)) / (sum(rate(state_bloom_filter_check_counts[$__rate_interval])) by (job,instance))",
     "legendFormat": "bloom filter hit rate - {{job}} @ {{instance}}"
    },
    {
     "expr": "((sum(rate(state_store_sst_store_block_request_counts{type='meta_total'}[$__rate_interval])) by (job,instance)) - (sum(rate(state_store_sst_store_block_request_counts{type='meta_miss'}[$__rate_interval])) by (job,instance))) / (sum(rate(state_store_sst_store_block_request_counts{type='meta_total'}[$__rate_interval])) by (job,instance))",
     "legendFormat": "meta cache hit rate - {{job}} @ {{instance}}"
    },
    {
     "expr": "((sum(rate(state_store_sst_store_block_request_counts{type='data_total'}[$__rate_interval])) by (job,instance)) - (sum(rate(state_store_sst_store_block_request_counts{type='data_miss'}[$__rate_interval])) by (job,instance))) / (sum(rate(state_store_sst_store_block_request_counts{type='data_total'}[$__rate_interval])) by (job,instance))",
     "legendFormat": "block cache hit rate - {{job}} @ {{instance}}"
    },
    {
     "expr": "((sum(rate(file_cache_get_latency_count[$__rate_interval])) by (instance)) - (sum(rate(file_cache_miss[$__rate_interval])) by (instance))) / (sum(rate(file_cache_get_latency_count[$__rate_interval])) by (instance))",
     "legendFormat": "file cache hit rate @ {{instance}}"
    }
   ]
  },
  {
   "title": "Read Merged SSTs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "sum by(le, job, instance)(rate(state_store_iter_merge_sstable_counts_sum[$__rate_interval]))  / sum by(le, job, instance)(rate(state_store_iter_merge_sstable_counts_count[$__rate_interval]))",
     "legendFormat": "# merged ssts avg  - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_duration_count[$__rate_interval])) by (job,instance)",
     "legendFormat": "write batch - {{job}} @ {{instance}} "
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_l0_duration_count[$__rate_interval])) by (job,instance)",
     "legendFormat": "l0 - {{job}} @ {{instance}} "
    }
   ]
  },
  {
   "title": "Write Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_batch_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "shared_buffer p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_batch_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "shared_buffer p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_batch_duration_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "shared_buffer p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_write_batch_duration_sum[$__rate_interval]))  / sum by(le, job, instance)(rate(state_store_write_batch_duration_count[$__rate_interval]))",
     "legendFormat": "shared_buffer avg - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(state_store_write_shared_buffer_sync_time_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "sync_remote p50 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(state_store_write_shared_buffer_sync_time_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "sync_remote p90 - {{job}} @ {{instance}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(state_store_write_shared_buffer_sync_time_bucket[$__rate_interval])) by (le, job, instance))",
     "legendFormat": "sync_remote p99 - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum by(le, job, instance)(rate(state_store_write_shared_buffer_sync_time_sum[$__rate_interval]))  / sum by(le, job, instance)(rate(state_store_write_shared_buffer_sync_time_count[$__rate_interval]))",
     "legendFormat": "sync_remote avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Write Item Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_tuple_counts[$__rate_interval])) by (job,instance)",
     "legendFormat": "write_batch_kv_pair_count - {{instance}} "
    }
   ]
  },
  {
   "title": "Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(state_store_write_batch_size_sum[$__rate_interval]))by(job,instance) / sum(rate(state_store_write_batch_size_count[$__rate_interval]))by(job,instance)",
     "legendFormat": "shared_buffer - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(rate(state_store_shared_buffer_to_sstable_size_sum[$__rate_interval]))by(job,instance) / sum(rate(state_store_shared_buffer_to_sstable_size_count[$__rate_interval]))by(job,instance)",
     "legendFormat": "sync - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint Sync Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(state_store_write_l0_size_per_epoch_sum[$__rate_interval])) / sum by(le, job, instance) (rate(state_store_write_l0_size_per_epoch_count[$__rate_interval]))",
     "legendFormat": "avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(state_store_meta_cache_size) by (job,instance)",
     "legendFormat": "meta cache - {{job}} @ {{instance}}"
    },
    {
     "expr": "avg(state_store_block_cache_size) by (job,instance)",
     "legendFormat": "data cache - {{job}} @ {{instance}}"
    },
    {
     "expr": "sum(state_store_limit_memory_size) by (job)",
     "legendFormat": "uploading memory - {{job}}"
    }
   ]
  },
  {
   "title": "Row SeqScan Next Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(le, job, instance) (rate(batch_row_seq_scan_next_duration_sum[$__rate_interval])) / sum by(le, job, instance) (rate(batch_row_seq_scan_next_duration_count[$__rate_interval]))",
     "legendFormat": "row_seq_scan next avg - {{job}} @ {{instance}}"
    }
   ]
  },
  {
   "title": "Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "SST Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(storage_level_sst_num) by (instance, level_index)",
       "legendFormat": "L{{level_index}}"
      }
     ]
    },
    {
     "title": "KBs level sst",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "sum(storage_level_total_file_size) by (instance, level_index)",
       "legendFormat": "L{{level_index}}"
      }
     ]
    },
    {
     "title": "Compaction Success & Failure Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(storage_level_compact_frequency) by (instance, group, result)",
       "legendFormat": "{{instance}} - {{result}} - group-{{group}}"
      }
     ]
    },
    {
     "title": "Compactor Running Task Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "avg(storage_compact_task_pending_num) by(job, instance)",
       "legendFormat": "compactor_task_split_count - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Compaction Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(state_store_compact_task_duration_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "compact-task p50 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_compact_task_duration_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "compact-task p90 - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum by(le)(rate(state_store_compact_task_duration_sum[$__rate_interval])) / sum by(le) (rate(state_store_compact_task_duration_count[$__rate_interval]))",
       "legendFormat": "compact-task avg"
      },
      {
       "expr": "sum by(le)(rate(state_store_compact_sst_duration_sum[$__rate_interval])) / sum by(le) (rate(state_store_compact_sst_duration_count[$__rate_interval]))",
       "legendFormat": "compact-key-range avg"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_compact_sst_duration_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "compact-key-range p90 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_get_table_id_total_time_duration_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "get-table-id p90 {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(state_store_remote_read_time_per_task_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "remote-io p90 - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Compaction Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_next[$__rate_interval])) by(job,instance) + sum(rate(storage_level_compact_read_curr[$__rate_interval])) by(job,instance)",
       "legendFormat": "read - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(storage_level_compact_write[$__rate_interval])) by(job,instance)",
       "legendFormat": "write - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(state_store_write_build_l0_bytes[$__rate_interval]))by (job,instance)",
       "legendFormat": "flush - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Compacting SST Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      { "expr": "storage_level_compact_cnt", "legendFormat": "L{{level_index}}" }
     ]
    },
    {
     "title": "KBs Read from Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_next[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "KBs Read from Current Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_curr[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "Count of SSTs Read from Current Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_sstn_curr[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "KBs Written to Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_write[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} write"
      }
     ]
    },
    {
     "title": "Count of SSTs Written to Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_write_sstn[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} write"
      }
     ]
    },
    {
     "title": "Count of SSTs Read from Next Level",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(storage_level_compact_read_sstn_next[$__rate_interval])) by (le, level_index)",
       "legendFormat": "L{{level_index}} read"
      }
     ]
    },
    {
     "title": "Hummock Version Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "version_size", "legendFormat": "version size" }
     ]
    },
    {
     "title": "Hummock Sstable BloomFilter Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(le, job, instance)(rate(state_store_sstable_bloom_filter_size_sum[$__rate_interval]))  / sum by(le, job, instance)(rate(state_store_sstable_bloom_filter_size_count[$__rate_interval]))",
       "legendFormat": "avg  - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Hummock Sstable Meta Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(le, job, instance)(rate(state_store_sstable_meta_size_sum[$__rate_interval]))  / sum by(le, job, instance)(rate(state_store_sstable_meta_size_count[$__rate_interval]))",
       "legendFormat": "avg  - {{job}} @ {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_read_bytes[$__rate_interval]))by(job,instance)",
       "legendFormat": "read - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(object_store_write_bytes[$__rate_interval]))by(job,instance)",
       "legendFormat": "write - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Operation Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(object_store_operation_latency_bucket[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}} p50"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(object_store_operation_latency_bucket[$__rate_interval])) by (le, type, job, instance))",
       "legendFormat": "{{type}} p99 - {{job}} @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_latency_bucket[$__rate_interval])) by (le, type, job, instance))",
       "legendFormat": "{{type}} p90 - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum by(le, type)(rate(object_store_operation_latency_sum[$__rate_interval])) / sum by(le, type) (rate(object_store_operation_latency_count[$__rate_interval]))",
       "legendFormat": "{{type}} avg"
      }
     ]
    },
    {
     "title": "Operation Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(object_store_operation_latency_count[$__rate_interval])) by (le, type, job, instance)",
       "legendFormat": "{{type}} - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(object_store_operation_latency_count{type=~'upload|delete'}[$__rate_interval])) by (le, media_type, job, instance)",
       "legendFormat": "{{media_type}}-write - {{job}} @ {{instance}}"
      },
      {
       "expr": "sum(rate(object_store_operation_latency_count{type=~'read|readv|list|metadata'}[$__rate_interval])) by (le, media_type, job, instance)",
       "legendFormat": "{{media_type}}-read - {{job}} @ {{instance}}"
      }
     ]
    },
    {
     "title": "Operation Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(object_store_operation_bytes_bucket[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}}  p90"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(object_store_operation_bytes_bucket[$__rate_interval])) by (le, type))",
       "legendFormat": "{{type}} p80"
      }
     ]
    },
    {
     "title": "Estimated S3 Cost (Realtime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "$" } },
     "targets": [
      {
       "expr": "sum(object_store_operation_latency_count{type=~'read|delete'}) * 0.0004 / 1000",
       "legendFormat": "GET + DELETE Request Cost"
      },
      {
       "expr": "sum(object_store_operation_latency_count{type='upload'}) * 0.005 / 1000",
       "legendFormat": "PUT Request Cost"
      }
     ]
    },
    {
     "title": "Estimated S3 Cost (Monthly)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "$" } },
     "targets": [
      {
       "expr": "sum(storage_level_total_file_size) by (instance) * 0.023 / 1000 / 1000",
       "legendFormat": "Monthly Storage Cost"
      }
     ]
    }
   ]
  },
  {
   "title": "Hummock Tiered Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(file_cache_get_latency_count[$__rate_interval])) by (instance)",
       "legendFormat": "file cache get @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_miss[$__rate_interval])) by (instance)",
       "legendFormat": "file cache miss @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_insert_latency_count[$__rate_interval])) by (instance)",
       "legendFormat": "file cache insert @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_erase_latency_count[$__rate_interval])) by (instance)",
       "legendFormat": "file cache erase @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_disk_read_latency_count[$__rate_interval])) by (instance)",
       "legendFormat": "file cache disk read @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_disk_write_latency_count[$__rate_interval])) by (instance)",
       "legendFormat": "file cache disk write @ {{instance}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_get_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p50 - file cache get @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_get_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p90 - file cache get @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_get_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p99 - file cache get @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_insert_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p50 - file cache insert @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_insert_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p90 - file cache insert @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_insert_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p99 - file cache insert @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_erase_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p50 - file cache erase @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_erase_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p90 - file cache erase @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_erase_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p99 - file cache erase @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_disk_read_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p50 - file cache disk read @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_disk_read_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p90 - file cache disk read @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_disk_read_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p99 - file cache disk read @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(file_cache_disk_write_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p50 - file cache disk write @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(file_cache_disk_write_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p90 - file cache disk write @ {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(file_cache_disk_write_latency_bucket[$__rate_interval])) by (le, instance))",
       "legendFormat": "p99 - file cache disk write @ {{instance}}"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(file_cache_disk_read_throughput[$__rate_interval])) by (instance)",
       "legendFormat": "disk read @ {{instance}}"
      },
      {
       "expr": "sum(rate(file_cache_disk_write_throughput[$__rate_interval])) by (instance)",
       "legendFormat": "disk write @ {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lock Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(hummock_manager_lock_time_bucket[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time p50 - {{lock_type}} {{lock_name}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(hummock_manager_lock_time_bucket[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time p99 - {{lock_type}} {{lock_name}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(hummock_manager_lock_time_bucket[$__rate_interval])) by (le, lock_name, lock_type))",
       "legendFormat": "Lock Time p999 - {{lock_type}} {{lock_name}}"
      }
     ]
    },
    {
     "title": "Real Process Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(meta_hummock_manager_real_process_time_bucket[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time P50 - {{method}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(meta_hummock_manager_real_process_time_bucket[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time P99 - {{method}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(meta_hummock_manager_real_process_time_bucket[$__rate_interval])) by (le, method))",
       "legendFormat": "Real Process Time P999 - {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Catalog Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "collapsed": true,
   "panels": [
    {
     "title": "create latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[$__rate_interval])) by (le))",
       "legendFormat": "Create_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[$__rate_interval])) by (le))",
       "legendFormat": "Create_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Create\"}[$__rate_interval])) by (le))",
       "legendFormat": "Create_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/Create\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/Create\"}[$__rate_interval]))",
       "legendFormat": "Create_avg"
      }
     ]
    },
    {
     "title": "drop latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[$__rate_interval])) by (le))",
       "legendFormat": "Drop_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[$__rate_interval])) by (le))",
       "legendFormat": "Drop_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/Drop\"}[$__rate_interval])) by (le))",
       "legendFormat": "Drop_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/Drop\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/Drop\"}[$__rate_interval]))",
       "legendFormat": "Drop_avg"
      }
     ]
    },
    {
     "title": "get catalog latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetCatalog_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetCatalog_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.CatalogService/GetCatalog\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetCatalog_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.CatalogService/GetCatalog\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.CatalogService/GetCatalog\"}[$__rate_interval]))",
       "legendFormat": "GetCatalog_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Cluster Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 },
   "collapsed": true,
   "panels": [
    {
     "title": "add worker node latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[$__rate_interval])) by (le))",
       "legendFormat": "AddWorkerNode_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[$__rate_interval])) by (le))",
       "legendFormat": "AddWorkerNode_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/AddWorkerNode\"}[$__rate_interval])) by (le))",
       "legendFormat": "AddWorkerNode_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.ClusterService/AddWorkerNode\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.ClusterService/AddWorkerNode\"}[$__rate_interval]))",
       "legendFormat": "AddWorkerNode_avg"
      }
     ]
    },
    {
     "title": "list all node latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[$__rate_interval])) by (le))",
       "legendFormat": "ListAllNodes_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[$__rate_interval])) by (le))",
       "legendFormat": "ListAllNodes_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.ClusterService/ListAllNodes\"}[$__rate_interval])) by (le))",
       "legendFormat": "ListAllNodes_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.ClusterService/ListAllNodes\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.ClusterService/ListAllNodes\"}[$__rate_interval]))",
       "legendFormat": "ListAllNodes_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Stream Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 },
   "collapsed": true,
   "panels": [
    {
     "title": "create materialized view latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[$__rate_interval])) by (le))",
       "legendFormat": "CreateMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[$__rate_interval])) by (le))",
       "legendFormat": "CreateMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[$__rate_interval])) by (le))",
       "legendFormat": "CreateMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/CreateMaterializedView\"}[$__rate_interval]))",
       "legendFormat": "CreateMaterializedView_avg"
      }
     ]
    },
    {
     "title": "drop materialized view latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[$__rate_interval])) by (le))",
       "legendFormat": "DropMaterializedView_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[$__rate_interval])) by (le))",
       "legendFormat": "DropMaterializedView_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/DropMaterializedView\"}[$__rate_interval])) by (le))",
       "legendFormat": "DropMaterializedView_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/DropMaterializedView\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/DropMaterializedView\"}[$__rate_interval]))",
       "legendFormat": "DropMaterializedView_avg"
      }
     ]
    },
    {
     "title": "flush latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[$__rate_interval])) by (le))",
       "legendFormat": "Flush_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[$__rate_interval])) by (le))",
       "legendFormat": "Flush_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/meta.StreamManagerService/Flush\"}[$__rate_interval])) by (le))",
       "legendFormat": "Flush_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/meta.StreamManagerService/Flush\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/meta.StreamManagerService/Flush\"}[$__rate_interval]))",
       "legendFormat": "Flush_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC Meta: Hummock Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "collapsed": true,
   "panels": [
    {
     "title": "version latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinVersion\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/UnpinVersion\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/UnpinVersion\"}[$__rate_interval]))",
       "legendFormat": "UnpinVersion_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[$__rate_interval])) by (le))",
       "legendFormat": "PinVersion_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[$__rate_interval])) by (le))",
       "legendFormat": "PinVersion_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinVersion\"}[$__rate_interval])) by (le))",
       "legendFormat": "PinVersion_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/PinVersion\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/PinVersion\"}[$__rate_interval]))",
       "legendFormat": "PinVersion_avg"
      }
     ]
    },
    {
     "title": "snapshot latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[$__rate_interval])) by (le))",
       "legendFormat": "UnpinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/UnpinSnapshot\"}[$__rate_interval]))",
       "legendFormat": "UnpinSnapshot_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[$__rate_interval])) by (le))",
       "legendFormat": "PinSnapshot_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[$__rate_interval])) by (le))",
       "legendFormat": "PinSnapshot_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/PinSnapshot\"}[$__rate_interval])) by (le))",
       "legendFormat": "PinSnapshot_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/PinSnapshot\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/PinSnapshot\"}[$__rate_interval]))",
       "legendFormat": "PinSnapshot_avg"
      }
     ]
    },
    {
     "title": "compaction latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[$__rate_interval])) by (le))",
       "legendFormat": "ReportCompactionTasks_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[$__rate_interval])) by (le))",
       "legendFormat": "ReportCompactionTasks_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[$__rate_interval])) by (le))",
       "legendFormat": "ReportCompactionTasks_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/ReportCompactionTasks\"}[$__rate_interval]))",
       "legendFormat": "ReportCompactionTasks_avg"
      }
     ]
    },
    {
     "title": "SST Id latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewSstIds\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetNewSstIds_p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewSstIds\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetNewSstIds_p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(meta_grpc_duration_seconds_bucket{path=\"/hummock.HummockManagerService/GetNewSstIds\"}[$__rate_interval])) by (le))",
       "legendFormat": "GetNewSstIds_p99"
      },
      {
       "expr": "sum(irate(meta_grpc_duration_seconds_sum{path=\"/hummock.HummockManagerService/GetNewSstIds\"}[$__rate_interval])) / sum(irate(meta_grpc_duration_seconds_count{path=\"/hummock.HummockManagerService/GetNewSstIds\"}[$__rate_interval]))",
       "legendFormat": "GetNewSstIds_avg"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC: Hummock Meta Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 },
   "collapsed": true,
   "panels": [
    {
     "title": "compaction_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum(irate(state_store_report_compaction_task_counts[$__rate_interval])) by(job,instance)",
       "legendFormat": "report_compaction_task_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "version_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_version_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pin_version_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_version_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pin_version_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_version_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pin_version_latencyp90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_version_latency_sum[$__rate_interval])) / sum(irate(state_store_pin_version_latency_count[$__rate_interval]))",
       "legendFormat": "pin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_latency_sum[$__rate_interval])) / sum(irate(state_store_unpin_version_latency_count[$__rate_interval]))",
       "legendFormat": "unpin_version_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_version_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "unpin_version_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "version_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_version_counts[$__rate_interval])) by(job,instance)",
       "legendFormat": "pin_version_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_version_counts[$__rate_interval])) by(job,instance)",
       "legendFormat": "unpin_version_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_pin_snapshot_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_pin_snapshot_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latency_p99 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.9, sum(irate(state_store_pin_snapshot_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "pin_snapshot_latencyp90 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_pin_snapshot_latency_sum[$__rate_interval])) / sum(irate(state_store_pin_snapshot_latency_count[$__rate_interval]))",
       "legendFormat": "pin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_unpin_version_snapshot_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_unpin_version_snapshot_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_latency_sum[$__rate_interval])) / sum(irate(state_store_unpin_snapshot_latency_count[$__rate_interval]))",
       "legendFormat": "unpin_snapshot_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_unpin_snapshot_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "unpin_snapshot_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "snapshot_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "sum(irate(state_store_pin_snapshot_counts[$__rate_interval])) by(job,instance)",
       "legendFormat": "pin_snapshot_counts - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_unpin_snapshot_counts[$__rate_interval])) by(job,instance)",
       "legendFormat": "unpin_snapshot_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "table_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_get_new_sst_ids_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "get_new_sst_ids_latency_latency_p50 - {{instance}} "
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_get_new_sst_ids_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "get_new_sst_ids_latency_latency_p99 - {{instance}} "
      },
      {
       "expr": "sum(irate(state_store_get_new_sst_ids_latency_sum[$__rate_interval])) / sum(irate(state_store_get_new_sst_ids_latency_count[$__rate_interval]))",
       "legendFormat": "get_new_sst_ids_latency_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_get_new_sst_ids_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "get_new_sst_ids_latency_latency_p90 - {{instance}} "
      }
     ]
    },
    {
     "title": "table_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(irate(state_store_get_new_sst_ids_latency_counts[$__rate_interval]))by(job,instance)",
       "legendFormat": "get_new_sst_ids_latency_counts - {{instance}} "
      }
     ]
    },
    {
     "title": "compaction_latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(state_store_report_compaction_task_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p50 - {{instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(state_store_report_compaction_task_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p99 - {{instance}}"
      },
      {
       "expr": "sum(irate(state_store_report_compaction_task_latency_sum[$__rate_interval])) / sum(irate(state_store_report_compaction_task_latency_count[$__rate_interval]))",
       "legendFormat": "report_compaction_task_latency_avg"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(state_store_report_compaction_task_latency_bucket[$__rate_interval])) by (le, job, instance))",
       "legendFormat": "report_compaction_task_latency_p90 - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Per second in Loacl Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "Qps" } },
     "targets": [
      {
       "expr": "rate(frontend_query_counter_local_execution[$__rate_interval])"
      }
     ]
    },
    {
     "title": "Query Average Latency in Local Execution Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "frontend_latency_local_execution_sum / frontend_latency_local_execution_count"
      }
     ]
    }
   ]
  }
 ]
}